[package]
name = "flowwatch"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
csv.workspace = true
directories.workspace = true
flowwatch-clash.workspace = true
flowwatch-core.workspace = true
flowwatch-macos.workspace = true
flowwatch-store.workspace = true
minreq.workspace = true
libc.workspace = true
plist.workspace = true
serde.workspace = true
serde_json.workspace = true
signal-hook.workspace = true
unicode-width.workspace = true
